In [1]:
import pandas as pd

In [5]:
df = pd.read_excel('./data/한국어_단발성_대화_데이터셋.xlsx', engine='openpyxl')
df

,Sentence,Emotion,Unnamed: 2,Unnamed: 3,Unnamed: 4,공포,5468
0,언니 동생으로 부르는게 맞는 일인가요..??,공포,NaN,NaN,NaN,놀람,5898.0
1,그냥 내 느낌일뿐겠지?,공포,NaN,NaN,NaN,분노,5665.0
2,아직너무초기라서 그런거죠?,공포,NaN,NaN,NaN,슬픔,5267.0
3,유치원버스 사고 낫다던데,공포,NaN,NaN,NaN,중립,4830.0
4,근데 원래이런거맞나요,공포,NaN,NaN,NaN,행복,6037.0
...,...,...,...,...,...,...,...
38589,솔직히 예보 제대로 못하는 데 세금이라도 아끼게 그냥 폐지해라..,혐오,NaN,NaN,NaN,NaN,NaN
38590,재미가 없으니 망하지,혐오,NaN,NaN,NaN,NaN,NaN
38591,공장 도시락 비우생적임 아르바이트했는데 화장실가성 손도 않씯고 재료 담고 바닥 떨어...,혐오,NaN,NaN,NaN,NaN,NaN
38592,코딱지 만한 나라에서 지들끼리 피터지게 싸우는 센징 클래스 ㅉㅉㅉ,혐오,NaN,NaN,NaN,NaN,NaN
38593,와이프도 그렇고 댓글 다 볼텐데 이휘재 좀 하차 하라고 전해주세요,혐오,NaN,NaN,NaN,NaN,NaN

In [9]:
df.columns

Index(['Sentence', 'Emotion', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', '공포',
       5468],
      dtype='object')

In [11]:
df = df.drop(columns=[ 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', '공포', 5468])

In [12]:
df

                                                Sentence Emotion
0                               언니 동생으로 부르는게 맞는 일인가요..??      공포
1                                           그냥 내 느낌일뿐겠지?      공포
2                                         아직너무초기라서 그런거죠?      공포
3                                          유치원버스 사고 낫다던데      공포
4                                            근데 원래이런거맞나요      공포
...                                                  ...     ...
38589               솔직히 예보 제대로 못하는 데 세금이라도 아끼게 그냥 폐지해라..      혐오
38590                                        재미가 없으니 망하지      혐오
38591  공장 도시락 비우생적임 아르바이트했는데 화장실가성 손도 않씯고 재료 담고 바닥 떨어...      혐오
38592               코딱지 만한 나라에서 지들끼리 피터지게 싸우는 센징 클래스 ㅉㅉㅉ      혐오
38593               와이프도 그렇고 댓글 다 볼텐데 이휘재 좀 하차 하라고 전해주세요      혐오

[38594 rows x 2 columns]

In [13]:
df.groupby('Emotion').count()

         Sentence
Emotion
공포           5468
놀람           5898
분노           5665
슬픔           5267
중립           4830
행복           6037
혐오           5429

In [15]:
df = df.drop(df[df['Emotion'] == '중립'].index)

In [16]:
df.groupby('Emotion').count()

         Sentence
Emotion
공포           5468
놀람           5898
분노           5665
슬픔           5267
행복           6037
혐오           5429

In [18]:
df.to_csv('./data/schat_6label.csv', index=True, encoding='utf-8')

In [20]:
df2 = pd.read_excel('./data/한국어_연속적_대화_데이터셋.xlsx', engine='openpyxl')
df2

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,행복,중립,슬픔,공포,혐오,분노,놀람
0,dialog #,발화,감정,NaN,NaN,1030.0,NaN,NaN,NaN,NaN,NaN,NaN
1,S,아 진짜! 사무실에서 피지 말라니깐! 간접흡연이 얼마나 안좋은데!,분노,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,그럼 직접흡연하는 난 얼마나 안좋겠니? 안그래? 보면 꼭... 지 생각만 하고.,혐오,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,손님 왔어요.,중립,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,손님? 누구?,중립,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
55624,S,얘긴 다 끝났냐? 원예부,중립,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55625,NaN,"예. 그거 때문에, 부탁이 있......는......데요.",중립,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55626,NaN,여자 숨겨달라는거면 사절이다.,중립,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55627,NaN,아무래도 안되나요?,중립,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55628,NaN,그 여자랑 내가 무슨 상관인데? 아까는 탐정님이 부탁하기에 너 구하는 김에 주워왔지...,중립,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
df2.columns

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       '행복', '중립', '슬픔', '공포', '혐오', '분노', '놀람'],
      dtype='object')

In [22]:
df2 = df2.drop(columns=['Unnamed: 0', 'Unnamed: 3', 'Unnamed: 4', '행복', '중립', '슬픔', '공포', '혐오', '분노', '놀람'])

In [23]:
df2

                                              Unnamed: 1 Unnamed: 2
0                                                     발화         감정
1                   아 진짜! 사무실에서 피지 말라니깐! 간접흡연이 얼마나 안좋은데!         분노
2           그럼 직접흡연하는 난 얼마나 안좋겠니? 안그래? 보면 꼭... 지 생각만 하고.         혐오
3                                                손님 왔어요.         중립
4                                                손님? 누구?         중립
...                                                  ...        ...
55624                                      얘긴 다 끝났냐? 원예부         중립
55625                   예. 그거 때문에, 부탁이 있......는......데요.         중립
55626                                   여자 숨겨달라는거면 사절이다.         중립
55627                                         아무래도 안되나요?         중립
55628  그 여자랑 내가 무슨 상관인데? 아까는 탐정님이 부탁하기에 너 구하는 김에 주워왔지...         중립

[55629 rows x 2 columns]

In [24]:
df2 = df2.rename(columns={'Unnamed: 1' : 'Sentence', 'Unnamed: 2' : 'Emotion'})

In [25]:
df2

                                                Sentence Emotion
0                                                     발화      감정
1                   아 진짜! 사무실에서 피지 말라니깐! 간접흡연이 얼마나 안좋은데!      분노
2           그럼 직접흡연하는 난 얼마나 안좋겠니? 안그래? 보면 꼭... 지 생각만 하고.      혐오
3                                                손님 왔어요.      중립
4                                                손님? 누구?      중립
...                                                  ...     ...
55624                                      얘긴 다 끝났냐? 원예부      중립
55625                   예. 그거 때문에, 부탁이 있......는......데요.      중립
55626                                   여자 숨겨달라는거면 사절이다.      중립
55627                                         아무래도 안되나요?      중립
55628  그 여자랑 내가 무슨 상관인데? 아까는 탐정님이 부탁하기에 너 구하는 김에 주워왔지...      중립

[55629 rows x 2 columns]

In [26]:
df2.groupby('Emotion').count()

         Sentence
Emotion
ㄴ중립             1
ㅈ중립             1
ㅍ              12
감정              1
공포             98
놀람           4866
분               4
분ㄴ              1
분노           3628
슬픔           1972
줄               1
중림              1
중립          43786
행복           1030
혐오            220

In [28]:
df2 = df2.drop(index=df2.loc[df2.Emotion == 'ㄴ중립'].index)
df2 = df2.drop(index=df2.loc[df2.Emotion == 'ㅈ중립'].index)
df2 = df2.drop(index=df2.loc[df2.Emotion == 'ㅍ'].index)
df2 = df2.drop(index=df2.loc[df2.Emotion == '감정'].index)
df2 = df2.drop(index=df2.loc[df2.Emotion == '공포'].index)
df2 = df2.drop(index=df2.loc[df2.Emotion == '분'].index)
df2 = df2.drop(index=df2.loc[df2.Emotion == '분ㄴ'].index)
df2 = df2.drop(index=df2.loc[df2.Emotion == '줄'].index)
df2 = df2.drop(index=df2.loc[df2.Emotion == '중림'].index)
df2 = df2.drop(index=df2.loc[df2.Emotion == '중립'].index)

In [29]:
df2.groupby('Emotion').count()

         Sentence
Emotion
놀람           4866
분노           3628
슬픔           1972
행복           1030
혐오            220

In [31]:
df2 = df2.drop(index=df2.loc[df2.Emotion == None].index)

In [32]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 11723 entries, 1 to 55610
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Sentence  11722 non-null  object
 1   Emotion   11716 non-null  object
dtypes: object(2)
memory usage: 274.8+ KB

In [34]:
df2 = df2.drop([3707, 30644, 31816, 46290, 47149, 48754, 50535])

In [36]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 11716 entries, 1 to 55610
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Sentence  11716 non-null  object
 1   Emotion   11716 non-null  object
dtypes: object(2)
memory usage: 274.6+ KB

In [35]:
df2.to_csv('./data/lchat_6label.csv', index=True, encoding='utf-8')

#### schat_6label, lchat_6label 합치기

#### 인덱스 재정렬

In [38]:
schat = pd.read_csv('./data/schat_6label.csv', index_col=0)
schat

                                                Sentence Emotion
0                               언니 동생으로 부르는게 맞는 일인가요..??      공포
1                                           그냥 내 느낌일뿐겠지?      공포
2                                         아직너무초기라서 그런거죠?      공포
3                                          유치원버스 사고 낫다던데      공포
4                                            근데 원래이런거맞나요      공포
...                                                  ...     ...
38589               솔직히 예보 제대로 못하는 데 세금이라도 아끼게 그냥 폐지해라..      혐오
38590                                        재미가 없으니 망하지      혐오
38591  공장 도시락 비우생적임 아르바이트했는데 화장실가성 손도 않씯고 재료 담고 바닥 떨어...      혐오
38592               코딱지 만한 나라에서 지들끼리 피터지게 싸우는 센징 클래스 ㅉㅉㅉ      혐오
38593               와이프도 그렇고 댓글 다 볼텐데 이휘재 좀 하차 하라고 전해주세요      혐오

[33764 rows x 2 columns]

In [39]:
lchat = pd.read_csv('./data/lchat_6label.csv', index_col=0)
lchat

                                           Sentence Emotion
1              아 진짜! 사무실에서 피지 말라니깐! 간접흡연이 얼마나 안좋은데!      분노
2      그럼 직접흡연하는 난 얼마나 안좋겠니? 안그래? 보면 꼭... 지 생각만 하고.      혐오
7                                    그걸 내가 어떻게 알아요!      분노
15                             동사무소에서 인구조사 나왔니? 지금.      분노
17                                  나? ... 나보고 하라고?      놀람
...                                             ...     ...
55567                                뭐? 다시 한 번 말해봐.      분노
55587                                       어? 정말요?      놀람
55589                           혹시, 다들 은행 계좌없는 거예요?      놀람
55604    자네는 대체 뭘 하러 왔나! 젖은 생쥐 꼴이 된 나를 보면서 비웃으러 왔나?      분노
55610                                           정말?      놀람

[11716 rows x 2 columns]

In [43]:
schat.reset_index(drop=True, inplace=True)

In [47]:
schat

                                                Sentence Emotion
0                               언니 동생으로 부르는게 맞는 일인가요..??      공포
1                                           그냥 내 느낌일뿐겠지?      공포
2                                         아직너무초기라서 그런거죠?      공포
3                                          유치원버스 사고 낫다던데      공포
4                                            근데 원래이런거맞나요      공포
...                                                  ...     ...
33759               솔직히 예보 제대로 못하는 데 세금이라도 아끼게 그냥 폐지해라..      혐오
33760                                        재미가 없으니 망하지      혐오
33761  공장 도시락 비우생적임 아르바이트했는데 화장실가성 손도 않씯고 재료 담고 바닥 떨어...      혐오
33762               코딱지 만한 나라에서 지들끼리 피터지게 싸우는 센징 클래스 ㅉㅉㅉ      혐오
33763               와이프도 그렇고 댓글 다 볼텐데 이휘재 좀 하차 하라고 전해주세요      혐오

[33764 rows x 2 columns]

In [48]:
lchat.reset_index(drop=True, inplace=True)

In [49]:
lchat

                                           Sentence Emotion
0              아 진짜! 사무실에서 피지 말라니깐! 간접흡연이 얼마나 안좋은데!      분노
1      그럼 직접흡연하는 난 얼마나 안좋겠니? 안그래? 보면 꼭... 지 생각만 하고.      혐오
2                                    그걸 내가 어떻게 알아요!      분노
3                              동사무소에서 인구조사 나왔니? 지금.      분노
4                                   나? ... 나보고 하라고?      놀람
...                                             ...     ...
11711                                뭐? 다시 한 번 말해봐.      분노
11712                                       어? 정말요?      놀람
11713                           혹시, 다들 은행 계좌없는 거예요?      놀람
11714    자네는 대체 뭘 하러 왔나! 젖은 생쥐 꼴이 된 나를 보면서 비웃으러 왔나?      분노
11715                                           정말?      놀람

[11716 rows x 2 columns]

In [51]:
chat = pd.concat([schat, lchat], ignore_index=True)
chat

                                         Sentence Emotion
0                        언니 동생으로 부르는게 맞는 일인가요..??      공포
1                                    그냥 내 느낌일뿐겠지?      공포
2                                  아직너무초기라서 그런거죠?      공포
3                                   유치원버스 사고 낫다던데      공포
4                                     근데 원래이런거맞나요      공포
...                                           ...     ...
45475                              뭐? 다시 한 번 말해봐.      분노
45476                                     어? 정말요?      놀람
45477                         혹시, 다들 은행 계좌없는 거예요?      놀람
45478  자네는 대체 뭘 하러 왔나! 젖은 생쥐 꼴이 된 나를 보면서 비웃으러 왔나?      분노
45479                                         정말?      놀람

[45480 rows x 2 columns]

In [52]:
chat.groupby('Emotion').count()

         Sentence
Emotion
공포           5468
놀람          10764
분노           9293
슬픔           7239
행복           7067
혐오           5649

In [53]:
chat.to_csv('./data/chat_6label.csv', index=True, encoding='utf-8')